---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      version: 2.7.6
  interval: 1m0s
  releaseName: rancher
  targetNamespace: cattle-system
  values:
    hostname: rancher.germanium.home
    tls: external
