apiVersion: v1
kind: Service
metadata:
  name: motioneye-service
  namespace: motioneye
  labels:
    app: motioneye
spec:
  selector:
    app: motioneye
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8765
