kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-etc-pv-claim
  namespace: motioneye
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: motioneye-lib-pv-claim
  namespace: motioneye
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
