---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    k8s-app: traefik-ingress-lb
    name: traefik-ingress-lb
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 8000
      protocol: TCP
    - name: websecure
      port: 8443
      protocol: TCP
    - name: traefik
      port: 9000
      protocol: TCP
