apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-scrypted
  name: my-scrypted
  namespace: default
spec:
  selector:
    app.kubernetes.io/instance: my-scrypted
    app.kubernetes.io/name: scrypted
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 10080
