apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsutils
  namespace: default
  labels:
    app: dnsutils
spec:
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: dnsutils
        image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
        command:
          - sleep
          - "infinity"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
