---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-v2
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1m0s
  releaseName: traefik
  targetNamespace: traefik-v2
  values:
    ingressRoute:
      dashboard:
        enabled: false
    # certResolvers:
    #   letsencrypt:
    #     email: petr.nemec@gmx.com
    #     dnsChallenge:
    #       provider: cloudflare
    #       delayBeforeCheck: 30
    #       resolvers:
    #         - 1.1.1.1
    #         - 8.8.8.8
    #     storage: /data/acme.json
    # env:
    # - name: CF_API_EMAIL
    #   valueFrom:
    #     secretKeyRef:
    #       name: cloudflare-api-email
    #       key: email
    # - name: CF_API_KEY
    #   valueFrom:
    #     secretKeyRef:
    #       name: cloudflare-api-key
    #       key: apikey
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
