apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack-bot
  namespace: flux-system
spec:
  type: slack
  channel: fluxcd
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: flux-slack-notification
