apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: flux-system
spec:
  selector:
    app: notification-controller
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9292
