apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegraf-mibs-pv
  namespace: telegraf
  labels:
    type: local
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp/telegraf"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegraf-mibs-pv-claim
  namespace: telegraf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
